# Generated by Django 3.2.3 on 2021-05-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='media/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee', verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('date_sales', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee', verbose_name='Продавец')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item', verbose_name='Товар')),
            ],
        ),
    ]
