# Generated by Django 3.2.3 on 2021-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
