# Generated by Django 3.2.3 on 2021-06-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_sale_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_sales']},
        ),
        migrations.CreateModel(
            name='UpdatedItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления цены')),
                ('updated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Новая цена')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item', verbose_name='Товар')),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
    ]
